# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message.proto',
  package='j_and_c',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rmessage.proto\x12\x07j_and_c\"8\n\tTimeStamp\x12\t\n\x01h\x18\x01 \x01(\x05\x12\t\n\x01m\x18\x02 \x01(\x05\x12\t\n\x01s\x18\x03 \x01(\x05\x12\n\n\x02ms\x18\x04 \x01(\x05\"v\n\x07Sensors\x12\n\n\x02id\x18\x01 \x01(\x05\x12%\n\ttimestamp\x18\x02 \x01(\x0b\x32\x12.j_and_c.TimeStamp\x12#\n\nsensortype\x18\x03 \x01(\x0e\x32\x0f.j_and_c.Sensor\x12\x13\n\x0bsensorvalue\x18\x04 \x01(\t\"a\n\x06Status\x12\n\n\x02id\x18\x01 \x01(\x05\x12%\n\ttimestamp\x18\x02 \x01(\x0b\x32\x12.j_and_c.TimeStamp\x12$\n\nsensordata\x18\x03 \x03(\x0b\x32\x10.j_and_c.Sensors*2\n\x06Sensor\x12\x07\n\x03GPS\x10\x00\x12\x06\n\x02US\x10\x01\x12\x0c\n\x08INFRARED\x10\x04\x12\t\n\x05LIDAR\x10\x08\x62\x06proto3'
)

_SENSOR = _descriptor.EnumDescriptor(
  name='Sensor',
  full_name='j_and_c.Sensor',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GPS', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='US', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INFRARED', index=2, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LIDAR', index=3, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=303,
  serialized_end=353,
)
_sym_db.RegisterEnumDescriptor(_SENSOR)

Sensor = enum_type_wrapper.EnumTypeWrapper(_SENSOR)
GPS = 0
US = 1
INFRARED = 4
LIDAR = 8



_TIMESTAMP = _descriptor.Descriptor(
  name='TimeStamp',
  full_name='j_and_c.TimeStamp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='h', full_name='j_and_c.TimeStamp.h', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='m', full_name='j_and_c.TimeStamp.m', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='s', full_name='j_and_c.TimeStamp.s', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ms', full_name='j_and_c.TimeStamp.ms', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=82,
)


_SENSORS = _descriptor.Descriptor(
  name='Sensors',
  full_name='j_and_c.Sensors',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='j_and_c.Sensors.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='j_and_c.Sensors.timestamp', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sensortype', full_name='j_and_c.Sensors.sensortype', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sensorvalue', full_name='j_and_c.Sensors.sensorvalue', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=202,
)


_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='j_and_c.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='j_and_c.Status.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='j_and_c.Status.timestamp', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sensordata', full_name='j_and_c.Status.sensordata', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=204,
  serialized_end=301,
)

_SENSORS.fields_by_name['timestamp'].message_type = _TIMESTAMP
_SENSORS.fields_by_name['sensortype'].enum_type = _SENSOR
_STATUS.fields_by_name['timestamp'].message_type = _TIMESTAMP
_STATUS.fields_by_name['sensordata'].message_type = _SENSORS
DESCRIPTOR.message_types_by_name['TimeStamp'] = _TIMESTAMP
DESCRIPTOR.message_types_by_name['Sensors'] = _SENSORS
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
DESCRIPTOR.enum_types_by_name['Sensor'] = _SENSOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TimeStamp = _reflection.GeneratedProtocolMessageType('TimeStamp', (_message.Message,), {
  'DESCRIPTOR' : _TIMESTAMP,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:j_and_c.TimeStamp)
  })
_sym_db.RegisterMessage(TimeStamp)

Sensors = _reflection.GeneratedProtocolMessageType('Sensors', (_message.Message,), {
  'DESCRIPTOR' : _SENSORS,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:j_and_c.Sensors)
  })
_sym_db.RegisterMessage(Sensors)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:j_and_c.Status)
  })
_sym_db.RegisterMessage(Status)


# @@protoc_insertion_point(module_scope)
