// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_message_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_message_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3015000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3015008 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_message_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_message_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_message_2eproto;
::PROTOBUF_NAMESPACE_ID::Metadata descriptor_table_message_2eproto_metadata_getter(int index);
namespace j_and_c {
class Sensors;
struct SensorsDefaultTypeInternal;
extern SensorsDefaultTypeInternal _Sensors_default_instance_;
class Status;
struct StatusDefaultTypeInternal;
extern StatusDefaultTypeInternal _Status_default_instance_;
class TimeStamp;
struct TimeStampDefaultTypeInternal;
extern TimeStampDefaultTypeInternal _TimeStamp_default_instance_;
}  // namespace j_and_c
PROTOBUF_NAMESPACE_OPEN
template<> ::j_and_c::Sensors* Arena::CreateMaybeMessage<::j_and_c::Sensors>(Arena*);
template<> ::j_and_c::Status* Arena::CreateMaybeMessage<::j_and_c::Status>(Arena*);
template<> ::j_and_c::TimeStamp* Arena::CreateMaybeMessage<::j_and_c::TimeStamp>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace j_and_c {

enum Sensor : int {
  GPS = 0,
  US = 1,
  INFRARED = 4,
  LIDAR = 8,
  Sensor_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  Sensor_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool Sensor_IsValid(int value);
constexpr Sensor Sensor_MIN = GPS;
constexpr Sensor Sensor_MAX = LIDAR;
constexpr int Sensor_ARRAYSIZE = Sensor_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Sensor_descriptor();
template<typename T>
inline const std::string& Sensor_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Sensor>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Sensor_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Sensor_descriptor(), enum_t_value);
}
inline bool Sensor_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Sensor* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Sensor>(
    Sensor_descriptor(), name, value);
}
// ===================================================================

class TimeStamp PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:j_and_c.TimeStamp) */ {
 public:
  inline TimeStamp() : TimeStamp(nullptr) {}
  virtual ~TimeStamp();
  explicit constexpr TimeStamp(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TimeStamp(const TimeStamp& from);
  TimeStamp(TimeStamp&& from) noexcept
    : TimeStamp() {
    *this = ::std::move(from);
  }

  inline TimeStamp& operator=(const TimeStamp& from) {
    CopyFrom(from);
    return *this;
  }
  inline TimeStamp& operator=(TimeStamp&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const TimeStamp& default_instance() {
    return *internal_default_instance();
  }
  static inline const TimeStamp* internal_default_instance() {
    return reinterpret_cast<const TimeStamp*>(
               &_TimeStamp_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(TimeStamp& a, TimeStamp& b) {
    a.Swap(&b);
  }
  inline void Swap(TimeStamp* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TimeStamp* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline TimeStamp* New() const final {
    return CreateMaybeMessage<TimeStamp>(nullptr);
  }

  TimeStamp* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<TimeStamp>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const TimeStamp& from);
  void MergeFrom(const TimeStamp& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TimeStamp* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "j_and_c.TimeStamp";
  }
  protected:
  explicit TimeStamp(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_message_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHFieldNumber = 1,
    kMFieldNumber = 2,
    kSFieldNumber = 3,
    kMsFieldNumber = 4,
  };
  // int32 h = 1;
  void clear_h();
  ::PROTOBUF_NAMESPACE_ID::int32 h() const;
  void set_h(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_h() const;
  void _internal_set_h(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 m = 2;
  void clear_m();
  ::PROTOBUF_NAMESPACE_ID::int32 m() const;
  void set_m(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_m() const;
  void _internal_set_m(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 s = 3;
  void clear_s();
  ::PROTOBUF_NAMESPACE_ID::int32 s() const;
  void set_s(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_s() const;
  void _internal_set_s(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 ms = 4;
  void clear_ms();
  ::PROTOBUF_NAMESPACE_ID::int32 ms() const;
  void set_ms(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_ms() const;
  void _internal_set_ms(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:j_and_c.TimeStamp)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::int32 h_;
  ::PROTOBUF_NAMESPACE_ID::int32 m_;
  ::PROTOBUF_NAMESPACE_ID::int32 s_;
  ::PROTOBUF_NAMESPACE_ID::int32 ms_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_message_2eproto;
};
// -------------------------------------------------------------------

class Sensors PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:j_and_c.Sensors) */ {
 public:
  inline Sensors() : Sensors(nullptr) {}
  virtual ~Sensors();
  explicit constexpr Sensors(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Sensors(const Sensors& from);
  Sensors(Sensors&& from) noexcept
    : Sensors() {
    *this = ::std::move(from);
  }

  inline Sensors& operator=(const Sensors& from) {
    CopyFrom(from);
    return *this;
  }
  inline Sensors& operator=(Sensors&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Sensors& default_instance() {
    return *internal_default_instance();
  }
  static inline const Sensors* internal_default_instance() {
    return reinterpret_cast<const Sensors*>(
               &_Sensors_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Sensors& a, Sensors& b) {
    a.Swap(&b);
  }
  inline void Swap(Sensors* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Sensors* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Sensors* New() const final {
    return CreateMaybeMessage<Sensors>(nullptr);
  }

  Sensors* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Sensors>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Sensors& from);
  void MergeFrom(const Sensors& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Sensors* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "j_and_c.Sensors";
  }
  protected:
  explicit Sensors(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_message_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSensorvalueFieldNumber = 4,
    kTimestampFieldNumber = 2,
    kIdFieldNumber = 1,
    kSensortypeFieldNumber = 3,
  };
  // string sensorvalue = 4;
  void clear_sensorvalue();
  const std::string& sensorvalue() const;
  void set_sensorvalue(const std::string& value);
  void set_sensorvalue(std::string&& value);
  void set_sensorvalue(const char* value);
  void set_sensorvalue(const char* value, size_t size);
  std::string* mutable_sensorvalue();
  std::string* release_sensorvalue();
  void set_allocated_sensorvalue(std::string* sensorvalue);
  private:
  const std::string& _internal_sensorvalue() const;
  void _internal_set_sensorvalue(const std::string& value);
  std::string* _internal_mutable_sensorvalue();
  public:

  // .j_and_c.TimeStamp timestamp = 2;
  bool has_timestamp() const;
  private:
  bool _internal_has_timestamp() const;
  public:
  void clear_timestamp();
  const ::j_and_c::TimeStamp& timestamp() const;
  ::j_and_c::TimeStamp* release_timestamp();
  ::j_and_c::TimeStamp* mutable_timestamp();
  void set_allocated_timestamp(::j_and_c::TimeStamp* timestamp);
  private:
  const ::j_and_c::TimeStamp& _internal_timestamp() const;
  ::j_and_c::TimeStamp* _internal_mutable_timestamp();
  public:
  void unsafe_arena_set_allocated_timestamp(
      ::j_and_c::TimeStamp* timestamp);
  ::j_and_c::TimeStamp* unsafe_arena_release_timestamp();

  // int32 id = 1;
  void clear_id();
  ::PROTOBUF_NAMESPACE_ID::int32 id() const;
  void set_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_id() const;
  void _internal_set_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // .j_and_c.Sensor sensortype = 3;
  void clear_sensortype();
  ::j_and_c::Sensor sensortype() const;
  void set_sensortype(::j_and_c::Sensor value);
  private:
  ::j_and_c::Sensor _internal_sensortype() const;
  void _internal_set_sensortype(::j_and_c::Sensor value);
  public:

  // @@protoc_insertion_point(class_scope:j_and_c.Sensors)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sensorvalue_;
  ::j_and_c::TimeStamp* timestamp_;
  ::PROTOBUF_NAMESPACE_ID::int32 id_;
  int sensortype_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_message_2eproto;
};
// -------------------------------------------------------------------

class Status PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:j_and_c.Status) */ {
 public:
  inline Status() : Status(nullptr) {}
  virtual ~Status();
  explicit constexpr Status(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Status(const Status& from);
  Status(Status&& from) noexcept
    : Status() {
    *this = ::std::move(from);
  }

  inline Status& operator=(const Status& from) {
    CopyFrom(from);
    return *this;
  }
  inline Status& operator=(Status&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Status& default_instance() {
    return *internal_default_instance();
  }
  static inline const Status* internal_default_instance() {
    return reinterpret_cast<const Status*>(
               &_Status_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Status& a, Status& b) {
    a.Swap(&b);
  }
  inline void Swap(Status* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Status* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Status* New() const final {
    return CreateMaybeMessage<Status>(nullptr);
  }

  Status* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Status>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Status& from);
  void MergeFrom(const Status& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Status* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "j_and_c.Status";
  }
  protected:
  explicit Status(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_message_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSensordataFieldNumber = 3,
    kTimestampFieldNumber = 2,
    kIdFieldNumber = 1,
  };
  // repeated .j_and_c.Sensors sensordata = 3;
  int sensordata_size() const;
  private:
  int _internal_sensordata_size() const;
  public:
  void clear_sensordata();
  ::j_and_c::Sensors* mutable_sensordata(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::j_and_c::Sensors >*
      mutable_sensordata();
  private:
  const ::j_and_c::Sensors& _internal_sensordata(int index) const;
  ::j_and_c::Sensors* _internal_add_sensordata();
  public:
  const ::j_and_c::Sensors& sensordata(int index) const;
  ::j_and_c::Sensors* add_sensordata();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::j_and_c::Sensors >&
      sensordata() const;

  // .j_and_c.TimeStamp timestamp = 2;
  bool has_timestamp() const;
  private:
  bool _internal_has_timestamp() const;
  public:
  void clear_timestamp();
  const ::j_and_c::TimeStamp& timestamp() const;
  ::j_and_c::TimeStamp* release_timestamp();
  ::j_and_c::TimeStamp* mutable_timestamp();
  void set_allocated_timestamp(::j_and_c::TimeStamp* timestamp);
  private:
  const ::j_and_c::TimeStamp& _internal_timestamp() const;
  ::j_and_c::TimeStamp* _internal_mutable_timestamp();
  public:
  void unsafe_arena_set_allocated_timestamp(
      ::j_and_c::TimeStamp* timestamp);
  ::j_and_c::TimeStamp* unsafe_arena_release_timestamp();

  // int32 id = 1;
  void clear_id();
  ::PROTOBUF_NAMESPACE_ID::int32 id() const;
  void set_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_id() const;
  void _internal_set_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:j_and_c.Status)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::j_and_c::Sensors > sensordata_;
  ::j_and_c::TimeStamp* timestamp_;
  ::PROTOBUF_NAMESPACE_ID::int32 id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_message_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TimeStamp

// int32 h = 1;
inline void TimeStamp::clear_h() {
  h_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TimeStamp::_internal_h() const {
  return h_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TimeStamp::h() const {
  // @@protoc_insertion_point(field_get:j_and_c.TimeStamp.h)
  return _internal_h();
}
inline void TimeStamp::_internal_set_h(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  h_ = value;
}
inline void TimeStamp::set_h(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_h(value);
  // @@protoc_insertion_point(field_set:j_and_c.TimeStamp.h)
}

// int32 m = 2;
inline void TimeStamp::clear_m() {
  m_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TimeStamp::_internal_m() const {
  return m_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TimeStamp::m() const {
  // @@protoc_insertion_point(field_get:j_and_c.TimeStamp.m)
  return _internal_m();
}
inline void TimeStamp::_internal_set_m(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  m_ = value;
}
inline void TimeStamp::set_m(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_m(value);
  // @@protoc_insertion_point(field_set:j_and_c.TimeStamp.m)
}

// int32 s = 3;
inline void TimeStamp::clear_s() {
  s_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TimeStamp::_internal_s() const {
  return s_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TimeStamp::s() const {
  // @@protoc_insertion_point(field_get:j_and_c.TimeStamp.s)
  return _internal_s();
}
inline void TimeStamp::_internal_set_s(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  s_ = value;
}
inline void TimeStamp::set_s(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_s(value);
  // @@protoc_insertion_point(field_set:j_and_c.TimeStamp.s)
}

// int32 ms = 4;
inline void TimeStamp::clear_ms() {
  ms_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TimeStamp::_internal_ms() const {
  return ms_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TimeStamp::ms() const {
  // @@protoc_insertion_point(field_get:j_and_c.TimeStamp.ms)
  return _internal_ms();
}
inline void TimeStamp::_internal_set_ms(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  ms_ = value;
}
inline void TimeStamp::set_ms(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_ms(value);
  // @@protoc_insertion_point(field_set:j_and_c.TimeStamp.ms)
}

// -------------------------------------------------------------------

// Sensors

// int32 id = 1;
inline void Sensors::clear_id() {
  id_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Sensors::_internal_id() const {
  return id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Sensors::id() const {
  // @@protoc_insertion_point(field_get:j_and_c.Sensors.id)
  return _internal_id();
}
inline void Sensors::_internal_set_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  id_ = value;
}
inline void Sensors::set_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:j_and_c.Sensors.id)
}

// .j_and_c.TimeStamp timestamp = 2;
inline bool Sensors::_internal_has_timestamp() const {
  return this != internal_default_instance() && timestamp_ != nullptr;
}
inline bool Sensors::has_timestamp() const {
  return _internal_has_timestamp();
}
inline void Sensors::clear_timestamp() {
  if (GetArena() == nullptr && timestamp_ != nullptr) {
    delete timestamp_;
  }
  timestamp_ = nullptr;
}
inline const ::j_and_c::TimeStamp& Sensors::_internal_timestamp() const {
  const ::j_and_c::TimeStamp* p = timestamp_;
  return p != nullptr ? *p : reinterpret_cast<const ::j_and_c::TimeStamp&>(
      ::j_and_c::_TimeStamp_default_instance_);
}
inline const ::j_and_c::TimeStamp& Sensors::timestamp() const {
  // @@protoc_insertion_point(field_get:j_and_c.Sensors.timestamp)
  return _internal_timestamp();
}
inline void Sensors::unsafe_arena_set_allocated_timestamp(
    ::j_and_c::TimeStamp* timestamp) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(timestamp_);
  }
  timestamp_ = timestamp;
  if (timestamp) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:j_and_c.Sensors.timestamp)
}
inline ::j_and_c::TimeStamp* Sensors::release_timestamp() {
  
  ::j_and_c::TimeStamp* temp = timestamp_;
  timestamp_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::j_and_c::TimeStamp* Sensors::unsafe_arena_release_timestamp() {
  // @@protoc_insertion_point(field_release:j_and_c.Sensors.timestamp)
  
  ::j_and_c::TimeStamp* temp = timestamp_;
  timestamp_ = nullptr;
  return temp;
}
inline ::j_and_c::TimeStamp* Sensors::_internal_mutable_timestamp() {
  
  if (timestamp_ == nullptr) {
    auto* p = CreateMaybeMessage<::j_and_c::TimeStamp>(GetArena());
    timestamp_ = p;
  }
  return timestamp_;
}
inline ::j_and_c::TimeStamp* Sensors::mutable_timestamp() {
  // @@protoc_insertion_point(field_mutable:j_and_c.Sensors.timestamp)
  return _internal_mutable_timestamp();
}
inline void Sensors::set_allocated_timestamp(::j_and_c::TimeStamp* timestamp) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete timestamp_;
  }
  if (timestamp) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(timestamp);
    if (message_arena != submessage_arena) {
      timestamp = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, timestamp, submessage_arena);
    }
    
  } else {
    
  }
  timestamp_ = timestamp;
  // @@protoc_insertion_point(field_set_allocated:j_and_c.Sensors.timestamp)
}

// .j_and_c.Sensor sensortype = 3;
inline void Sensors::clear_sensortype() {
  sensortype_ = 0;
}
inline ::j_and_c::Sensor Sensors::_internal_sensortype() const {
  return static_cast< ::j_and_c::Sensor >(sensortype_);
}
inline ::j_and_c::Sensor Sensors::sensortype() const {
  // @@protoc_insertion_point(field_get:j_and_c.Sensors.sensortype)
  return _internal_sensortype();
}
inline void Sensors::_internal_set_sensortype(::j_and_c::Sensor value) {
  
  sensortype_ = value;
}
inline void Sensors::set_sensortype(::j_and_c::Sensor value) {
  _internal_set_sensortype(value);
  // @@protoc_insertion_point(field_set:j_and_c.Sensors.sensortype)
}

// string sensorvalue = 4;
inline void Sensors::clear_sensorvalue() {
  sensorvalue_.ClearToEmpty();
}
inline const std::string& Sensors::sensorvalue() const {
  // @@protoc_insertion_point(field_get:j_and_c.Sensors.sensorvalue)
  return _internal_sensorvalue();
}
inline void Sensors::set_sensorvalue(const std::string& value) {
  _internal_set_sensorvalue(value);
  // @@protoc_insertion_point(field_set:j_and_c.Sensors.sensorvalue)
}
inline std::string* Sensors::mutable_sensorvalue() {
  // @@protoc_insertion_point(field_mutable:j_and_c.Sensors.sensorvalue)
  return _internal_mutable_sensorvalue();
}
inline const std::string& Sensors::_internal_sensorvalue() const {
  return sensorvalue_.Get();
}
inline void Sensors::_internal_set_sensorvalue(const std::string& value) {
  
  sensorvalue_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void Sensors::set_sensorvalue(std::string&& value) {
  
  sensorvalue_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:j_and_c.Sensors.sensorvalue)
}
inline void Sensors::set_sensorvalue(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  sensorvalue_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:j_and_c.Sensors.sensorvalue)
}
inline void Sensors::set_sensorvalue(const char* value,
    size_t size) {
  
  sensorvalue_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:j_and_c.Sensors.sensorvalue)
}
inline std::string* Sensors::_internal_mutable_sensorvalue() {
  
  return sensorvalue_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* Sensors::release_sensorvalue() {
  // @@protoc_insertion_point(field_release:j_and_c.Sensors.sensorvalue)
  return sensorvalue_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Sensors::set_allocated_sensorvalue(std::string* sensorvalue) {
  if (sensorvalue != nullptr) {
    
  } else {
    
  }
  sensorvalue_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), sensorvalue,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:j_and_c.Sensors.sensorvalue)
}

// -------------------------------------------------------------------

// Status

// int32 id = 1;
inline void Status::clear_id() {
  id_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Status::_internal_id() const {
  return id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Status::id() const {
  // @@protoc_insertion_point(field_get:j_and_c.Status.id)
  return _internal_id();
}
inline void Status::_internal_set_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  id_ = value;
}
inline void Status::set_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:j_and_c.Status.id)
}

// .j_and_c.TimeStamp timestamp = 2;
inline bool Status::_internal_has_timestamp() const {
  return this != internal_default_instance() && timestamp_ != nullptr;
}
inline bool Status::has_timestamp() const {
  return _internal_has_timestamp();
}
inline void Status::clear_timestamp() {
  if (GetArena() == nullptr && timestamp_ != nullptr) {
    delete timestamp_;
  }
  timestamp_ = nullptr;
}
inline const ::j_and_c::TimeStamp& Status::_internal_timestamp() const {
  const ::j_and_c::TimeStamp* p = timestamp_;
  return p != nullptr ? *p : reinterpret_cast<const ::j_and_c::TimeStamp&>(
      ::j_and_c::_TimeStamp_default_instance_);
}
inline const ::j_and_c::TimeStamp& Status::timestamp() const {
  // @@protoc_insertion_point(field_get:j_and_c.Status.timestamp)
  return _internal_timestamp();
}
inline void Status::unsafe_arena_set_allocated_timestamp(
    ::j_and_c::TimeStamp* timestamp) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(timestamp_);
  }
  timestamp_ = timestamp;
  if (timestamp) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:j_and_c.Status.timestamp)
}
inline ::j_and_c::TimeStamp* Status::release_timestamp() {
  
  ::j_and_c::TimeStamp* temp = timestamp_;
  timestamp_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::j_and_c::TimeStamp* Status::unsafe_arena_release_timestamp() {
  // @@protoc_insertion_point(field_release:j_and_c.Status.timestamp)
  
  ::j_and_c::TimeStamp* temp = timestamp_;
  timestamp_ = nullptr;
  return temp;
}
inline ::j_and_c::TimeStamp* Status::_internal_mutable_timestamp() {
  
  if (timestamp_ == nullptr) {
    auto* p = CreateMaybeMessage<::j_and_c::TimeStamp>(GetArena());
    timestamp_ = p;
  }
  return timestamp_;
}
inline ::j_and_c::TimeStamp* Status::mutable_timestamp() {
  // @@protoc_insertion_point(field_mutable:j_and_c.Status.timestamp)
  return _internal_mutable_timestamp();
}
inline void Status::set_allocated_timestamp(::j_and_c::TimeStamp* timestamp) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete timestamp_;
  }
  if (timestamp) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(timestamp);
    if (message_arena != submessage_arena) {
      timestamp = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, timestamp, submessage_arena);
    }
    
  } else {
    
  }
  timestamp_ = timestamp;
  // @@protoc_insertion_point(field_set_allocated:j_and_c.Status.timestamp)
}

// repeated .j_and_c.Sensors sensordata = 3;
inline int Status::_internal_sensordata_size() const {
  return sensordata_.size();
}
inline int Status::sensordata_size() const {
  return _internal_sensordata_size();
}
inline void Status::clear_sensordata() {
  sensordata_.Clear();
}
inline ::j_and_c::Sensors* Status::mutable_sensordata(int index) {
  // @@protoc_insertion_point(field_mutable:j_and_c.Status.sensordata)
  return sensordata_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::j_and_c::Sensors >*
Status::mutable_sensordata() {
  // @@protoc_insertion_point(field_mutable_list:j_and_c.Status.sensordata)
  return &sensordata_;
}
inline const ::j_and_c::Sensors& Status::_internal_sensordata(int index) const {
  return sensordata_.Get(index);
}
inline const ::j_and_c::Sensors& Status::sensordata(int index) const {
  // @@protoc_insertion_point(field_get:j_and_c.Status.sensordata)
  return _internal_sensordata(index);
}
inline ::j_and_c::Sensors* Status::_internal_add_sensordata() {
  return sensordata_.Add();
}
inline ::j_and_c::Sensors* Status::add_sensordata() {
  // @@protoc_insertion_point(field_add:j_and_c.Status.sensordata)
  return _internal_add_sensordata();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::j_and_c::Sensors >&
Status::sensordata() const {
  // @@protoc_insertion_point(field_list:j_and_c.Status.sensordata)
  return sensordata_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace j_and_c

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::j_and_c::Sensor> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::j_and_c::Sensor>() {
  return ::j_and_c::Sensor_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_message_2eproto
