# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service.proto',
  package='j_and_c',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rservice.proto\x12\x07j_and_c\"\x1a\n\x0bTimeRequest\x12\x0b\n\x03req\x18\x01 \x01(\t\"8\n\x0cTimeResponse\x12\x15\n\rtime_received\x18\x01 \x01(\x01\x12\x11\n\ttime_sent\x18\x02 \x01(\x01\x32\x45\n\x07GetTime\x12:\n\tGimmeTime\x12\x14.j_and_c.TimeRequest\x1a\x15.j_and_c.TimeResponse\"\x00\x62\x06proto3'
)




_TIMEREQUEST = _descriptor.Descriptor(
  name='TimeRequest',
  full_name='j_and_c.TimeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='req', full_name='j_and_c.TimeRequest.req', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=52,
)


_TIMERESPONSE = _descriptor.Descriptor(
  name='TimeResponse',
  full_name='j_and_c.TimeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='time_received', full_name='j_and_c.TimeResponse.time_received', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time_sent', full_name='j_and_c.TimeResponse.time_sent', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=110,
)

DESCRIPTOR.message_types_by_name['TimeRequest'] = _TIMEREQUEST
DESCRIPTOR.message_types_by_name['TimeResponse'] = _TIMERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TimeRequest = _reflection.GeneratedProtocolMessageType('TimeRequest', (_message.Message,), {
  'DESCRIPTOR' : _TIMEREQUEST,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:j_and_c.TimeRequest)
  })
_sym_db.RegisterMessage(TimeRequest)

TimeResponse = _reflection.GeneratedProtocolMessageType('TimeResponse', (_message.Message,), {
  'DESCRIPTOR' : _TIMERESPONSE,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:j_and_c.TimeResponse)
  })
_sym_db.RegisterMessage(TimeResponse)



_GETTIME = _descriptor.ServiceDescriptor(
  name='GetTime',
  full_name='j_and_c.GetTime',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=112,
  serialized_end=181,
  methods=[
  _descriptor.MethodDescriptor(
    name='GimmeTime',
    full_name='j_and_c.GetTime.GimmeTime',
    index=0,
    containing_service=None,
    input_type=_TIMEREQUEST,
    output_type=_TIMERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GETTIME)

DESCRIPTOR.services_by_name['GetTime'] = _GETTIME

# @@protoc_insertion_point(module_scope)
