# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import service_pb2 as service__pb2


class GetTimeStub(object):
    """Timestamp
    see https://users.pja.edu.pl/~jms/qnx/help/watcom/clibref/qnx/clock_gettime.html
    The clock_gettime() function gets the current time of the clock specified by clock_id, and puts it into the buffer pointed to by tp. The only supported clock ID is CLOCK_REALTIME.
    The tp parameter points to a structure containing at least the following members:
    time_t tv_sec
    The number of seconds since 1970.
    time_t tv_nsec
    The number of nanoseconds expired in the current second. This value increases by some multiple of nanoseconds, based on the system clock's resolution.

    The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GimmeTime = channel.unary_unary(
                '/j_and_c.GetTime/GimmeTime',
                request_serializer=service__pb2.TimeRequest.SerializeToString,
                response_deserializer=service__pb2.TimeResponse.FromString,
                )


class GetTimeServicer(object):
    """Timestamp
    see https://users.pja.edu.pl/~jms/qnx/help/watcom/clibref/qnx/clock_gettime.html
    The clock_gettime() function gets the current time of the clock specified by clock_id, and puts it into the buffer pointed to by tp. The only supported clock ID is CLOCK_REALTIME.
    The tp parameter points to a structure containing at least the following members:
    time_t tv_sec
    The number of seconds since 1970.
    time_t tv_nsec
    The number of nanoseconds expired in the current second. This value increases by some multiple of nanoseconds, based on the system clock's resolution.

    The greeting service definition.
    """

    def GimmeTime(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GetTimeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GimmeTime': grpc.unary_unary_rpc_method_handler(
                    servicer.GimmeTime,
                    request_deserializer=service__pb2.TimeRequest.FromString,
                    response_serializer=service__pb2.TimeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'j_and_c.GetTime', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GetTime(object):
    """Timestamp
    see https://users.pja.edu.pl/~jms/qnx/help/watcom/clibref/qnx/clock_gettime.html
    The clock_gettime() function gets the current time of the clock specified by clock_id, and puts it into the buffer pointed to by tp. The only supported clock ID is CLOCK_REALTIME.
    The tp parameter points to a structure containing at least the following members:
    time_t tv_sec
    The number of seconds since 1970.
    time_t tv_nsec
    The number of nanoseconds expired in the current second. This value increases by some multiple of nanoseconds, based on the system clock's resolution.

    The greeting service definition.
    """

    @staticmethod
    def GimmeTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/j_and_c.GetTime/GimmeTime',
            service__pb2.TimeRequest.SerializeToString,
            service__pb2.TimeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
